### ISSUE TITLE
As a user, I want each event I go to to have a detail page

### ISSUE THREAD

**Issue by arpitab** [DustyWindBro/mgt656-spring-2015-project#45]

**Comment by byoung15** [comment]
Was spinning my wheels for this so will go to the TA session tonight to determine how to to do this.

**Comment by byoung15** [comment]
This is complicated - didn't even make sense with a TA standing over me.  Here is some of the gist that he told me:

Look up express JS routes parameters in Google for more information.
Need to create a new file under views to create a new file - but that file needs to route to a new page as new events will constantly be created.
